config/routes.rb
Rails.application.routes.draw do
  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out
  get '/' => "questions#index"

  resources :users do
    resources :questions
    resources :answers
  end

  resources :questions do
    resources :answers
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :answerable, polymorphic: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers, as: :answerable
  validates :question, :title, :presence => true
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  include BCrypt
  has_many :questions
  has_many :answers, as: :answerable
  validates :name, :password, :presence => true

  def password
    @password ||= Password.new(password_hash)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end

  def add_view
    self.profile_views = self.profile_views + 1
  end

  def self.authenticate(name, password)
    user = User.where(name: name).first
    if user.password == password
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
    @user = User.find(params[:user_id])
  end

  def create
    @user = User.find(params[:user_id])
    @question = Question.new(question_params)
    @user.questions.push(@question)
    if @user.save
      redirect_to questions_path
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to questions_path
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end

private
  def question_params
    params.require(:question).permit(:question, :title, :user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.authenticate(params[:name], params[:password])
    if @user
      flash[:notice] = "You've been logged in."
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem logging you in."
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @user.add_view
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.password = user_params[:password]
    if @user.save!
      flash[:notice] = "Welcome to the site!"
      redirect_to users_path
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  def login
    @user = User.find_by_name(params[:name])
    if @user.password == params[:password]
      session[:user_id] = @user.id
    else
      redirect_to users_path
    end
  end

private
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<div class="error_explanation">
  <h2>
    <%= pluralize(object.errors.count, "error") %>
    prohibited your request from being saved:
  </h2>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stackoverflow</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" >
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><img src="https://cdn.sstatic.net/Sites/stackoverflow/company/img/logos/so/so-icon.png?v=c78bd457575a" alt="" class="brand-logo"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  <div class="container">
    <% if session[:user_id] %>
      <h1> <%= User.find(session[:user_id]).name %> </h1>
    <% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= render 'layouts/errors', :object => @question  %>

<%= form_for  [@user, @question]  do |f|  %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :question %>
    <%= f.text_area :question, class: 'form-control' %>
  </div>

  <%= f.submit class: 'button' %>
<% end %>

app/views/questions/index.html.erb
  <div class="row">
    <div class="col-md-9">
      <% @questions.each do |question| %>
      <div class="question-wrapper">
        <%= link_to(question_path(question)) do %>
          <h3><%= question.title %></h3>
        <% end %>

        <p class="question-excerpt"><%= question.question %></p>

        <%= link_to(user_path(question.user_id)) do %>
          <p class="user"> <%= question.user.name %> </p>
        <% end %>
        <div class="rating">
          <p> <%= question.rating %> </p>
        </div>
        <div class="answers">
          <p><%= question.answers.count %></p>
        </div>
      </div>
      <% end %>
    </div>
    <div class="col-md-3">
      <div class="box">

      </div>
    </div>
  </div>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<h2> <%= @quesiton.title %> </h2>
<hr>
<div class="container">
  <div class="row">
    <div class="col-md-9">
      <div class="rating">
        <i class="fa fa-chevron-up fa-4x"></i>
        <%= @question.rating %>
        <i class="fa fa-chevron-down fa-4x"></i>
      </div>
      <div class="question">
        <p><%= @question.question %></p>
      </div>
    </div>
    <div class="col-md-3">
      <p>Salvia pour-over +1, disrupt art party flannel ramps organic distillery before they sold out bespoke heirloom. Ennui tousled XOXO kickstarter, franzen irony yr fam banh mi wayfarers chambray live-edge hella whatever snackwave. Kinfolk farm-to-table scenester keytar mixtape +1. Subway tile narwhal portland microdosing kitsch cold-pressed, lo-fi ennui crucifix enamel pin williamsburg seitan XOXO cardigan sartorial. Sartorial gastropub raclette offal ennui mlkshk. Cronut franzen flannel schlitz blue bottle. Brunch yr cronut, man braid stumptown tattooed YOLO.</p>
    </div>
  </div>

</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%=form_for User.new do |f| %>

<%=f.label :email %>

<%=f.text_field :email %>

<%=f.label :password %>

<%=f.password_field :password %>

<%=f.label :password_confirmation %>

<%=f.password_field :password_confirmation %>

<%=f.submit "Sign Up" %>

<%end%>